// Single source of truth for the set of grantable permission strings, shared
// by GlobalUser's per-brand-membership permissions and CustomRole's bundles
// so the two never drift apart.
const ALL_PERMISSIONS = Object.freeze([
  "all",
  "overall_snapshot",
  "requests_panel",
  "requests_timeline",
  "bundles_panel",
  "inventory_panel",
  "daily_funnel_panel",
  "utm_funnel_table",
  "utm_funnel_table:utm_campaign_grain",
  "product_filter",
  "utm_filter",
  "product_utm_filter_sync",
  "discount_filter",
  "intent_metrics",
  "dashboard_layout_customize",
  "session_analytics",
  "web_vitals",
  "payment_split_order",
  "payment_split_sales",
  "traffic_split",
  "sales_channel_filter",
  "device_type_filter",
  "product_type_filter",
  "city_filter",
  "ci_events",
  "rto_kpi",
  "sessions_drop_off_funnel",
  "product_conversion",
  "compare_mode",
  "multiselectable_kpi_cards",
  "product_conversion:landing_page_path",
  "product_conversion:sessions",
  "product_conversion:atc",
  "product_conversion:atc_rate",
  "product_conversion:orders",
  "product_conversion:sales",
  "product_conversion:cvr",
  "product_conversion:drr",
  "product_conversion:doh",
  "product_table_filters",
  "product_table_filters:inventory",
  "product_table_filters:page_type",
  "product_table_filters:product_types",
  "product_table_filters:sort_filter",
  "daily_insight_view",
  "health_monitor_panel",
]);

module.exports = { ALL_PERMISSIONS };
